### ISSUE TITLE
[Feature Request] Textual inversion embeddings skipped

### ISSUE THREAD

**Issue by brunogcar** [CurtisDS/sd-model-preview-xd#1]
Depending on if model is 1.x or 2.x WebUI loads respective compatible embeddings 

Currently in embeddings tab it just shows Textual inversion embeddings loaded

but as the extension goal IMO  seems to be to display info, pics on all Checkpoints, TI, HT and Lora, it would be a good addition 
 to also display Textual inversion embeddings skipped as well, as extra skipped tab?

pretty sure you know how to get it, but as reference

https://github.com/vladmandic/sd-extension-system-info

does it

**Comment by CurtisDS** [comment]
Hmmmmm, I didn't actually know about the fact that there were embeddings specific to 2.x models. I have a few and saw the console say "skipped" but figured "Ill look into that later" lol (haven't really been playing with 2.x models much).

If you want to see the 2.x embeddings you can get them to show by switching to a 2.x checkpoint, waiting for it to load, then go into the extra network panel and hit `Refresh` (its interesting that automaic1111 doesnt reload them in the webui automatically).... it should update the preview embedding list to include the 2.x embeddings... but obviously it then hides the 1.x embeddings. 

And when I just did that I noticed a new bug that is causing only some of the embeddings to show in the list after you hit the refresh button.... odd. (* If anyone runs into this before I fix it just go to settings and hit `Reload UI` to fix the preview embeddings list *)

I don't know which way is better but I am leaning towards showing both the loaded and the skipped embeddings in the one tab. I will look into updating that.

**Comment by CurtisDS** [comment]
This has now been implemented (as of commit c0e8be42ddf231a90ed4d4d2064ebe00c4d9bd50). Also I forgot to increment the version in that commit message but oh well, now there are two with the title v1.0.3. I have also made other changes along with fixing the bug I was talking about.

Thanks for letting me know about the skipped embeddings.
