### ISSUE TITLE
[Possible bug]: LoRA section not showing previews

### ISSUE THREAD

**Issue by Woisek** [CurtisDS/sd-model-preview-xd#10]
The LoRA section of the preview page doesnt show any text or image files from the folders where the models are saved.
Checkpoint, Hypernetwork and Embedding work as intended.

In the LoRA section, the list shows all models twice: Once just the name, beneath name and hash. No display, no matter which entry is selected (attached scrrenshot).

Automatic1111 commit -> https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
I use the "Additional network" addon -> https://github.com/kohya-ss/sd-webui-additional-networks.git

**Update:** While I'm writing this, I checked for myself what's happening if I disable the extension.
And, what can I say, after deactivating it, the display for LoRAs works.

So, I guess then this isn't a bug, but rather a conflict. of the extension.
But to be honest, I somehow like the extension, because of the tab with those whole bunch of infos I can have for the models. If you can manage to sort this issue easily, please do so. Otherwise I have to switch this extension off and on. Not very convenient, but ... well ... :)
![preview](https://user-images.githubusercontent.com/122026301/221141858-195d289b-ed52-430e-a404-3063d6dbf8ef.png)

**Comment by CurtisDS** [comment]
I was able to fix this. It will break support for older versions of the additional network extension though. I dont know what version broke it but just make sure your additional network extension is up to date and it should work after updating the preview extension.

**Comment by Woisek** [comment]
@CurtisDS 
Hey, thanks for this quick fix. The display is now working, with a minor issue: While the entries are now single, like it shoud, the previews now getting displayed twice ... :D
I guess there is still something left from the additional network that causes this. It's not a big deal, just aestethics. ;)

**Comment by CurtisDS** [comment]
Ah, I didnt notice because I use HTML previews which are limited to one so cant be doubled up. This update should fix it.

**Comment by Woisek** [comment]
Many thanks, is now working as intended. 👍
