### ISSUE TITLE
I'm developing something: MgM (Model Gallery Maker) {collaboration} 

### ISSUE THREAD

**Issue by cibernicola** [CurtisDS/sd-model-preview-xd#11]
Hello, since a few days ago I am developing a plugin for WebUI whose function is to generate a gallery for the models downloaded from civitai.com.
It parses the Json data of each model and generates an html.
It is in embryonic stage but it is functional and, together with model-preview-xd, it works quite well.

I have several more ideas to improve it, maybe we could collaborate?

some examples:

![image](https://user-images.githubusercontent.com/4579387/221353757-968567a9-c302-4871-85e3-5eba1b16f51b.png)
![image](https://user-images.githubusercontent.com/4579387/221353766-78835e49-f1c2-4f93-a306-439b6f0edb16.png)
![image](https://user-images.githubusercontent.com/4579387/221353783-f138ed37-d847-4317-b9c1-46c29cbcffa3.png)

it is a fact that model management is a problem as well as something very important and useful.

**Comment by CurtisDS** [comment]
For me personally, I wrote something that scrapes civitai and creates an minimal offline version of their web page:
![image](https://user-images.githubusercontent.com/20732674/221368636-203cd972-e632-4cd2-870e-5841664d23ee.png)

What did you have in mind in terms of collaborating?

**Comment by cibernicola** [comment]
Integrate mgm inside model preview, for example, in order to automaitze and optmize as much as possible sort, get, an use all galeries.

**Comment by CurtisDS** [comment]
Thanks for the suggestion but right now Im going to decline. While Civitai is a great site for getting models from its not the only site to get models from so this feature wouldn't work for everyone. And to be honest, if I were going to do something like this I would probably adapt my own code that I'm already using. There are a couple reasons why I havent already done that:

1. Civitai is changing regularly and so the extension would require a lot more maintenance.
2. Some people are very particular with how they want things to look, so you're not going to please everyone anyway. And if someone isn't particular with how they want things to look they can always just use Ctrl+S on the civitai page right now and save the current page, with images, instructions and trigger words to use as their preview page without me having to do anything.

But by all means continue to work on your extension. Even as a separate extension I'm sure it would help some people.

**Comment by TFWol** [comment]
> For me personally, I wrote something that scrapes civitai and creates an minimal offline version of their web page

@CurtisDS 
Nice. Would you mind sharing the snippet? Would be better than the time consuming thing I'm doing.

**Comment by CurtisDS** [comment]
@TFWol here is the code I use to create my preview pages for models from civitai: https://github.com/CurtisDS/minified-civitai/

**Comment by TFWol** [comment]
Sweet! Thanks a bunch, I'll be trying this out shortly.

**Comment by cibernicola** [comment]
I am close to finishing something, the idea is to unify criteria and efforts:
Unite the work done by Civitai Helper, create a decent gallery locally that is accessible in the model preview tab xD.

An example:
![image](https://user-images.githubusercontent.com/4579387/225575782-a6480f7b-933d-48f5-aa92-c3d3ace0b870.png)

**Comment by unai-ndz** [comment]
Quick and dirty wrapper around [minified-civitai/](https://github.com/CurtisDS/minified-civitai/) to calculate the hashes of the models in a folder and match them to ids for minified-civitai to use.
It also generates a simple .md with some info about the model and downloads the preview images, both in the folder where each model is located.

https://gist.github.com/unai-ndz/ca380c7aa65c9f2aa3b55df2bb0faab1
![screenshots_3](https://user-images.githubusercontent.com/29188654/227726384-cb5b1940-2a03-48aa-8287-26d07fea8f47.png)

**Comment by CurtisDS** [comment]
> Quick and dirty wrapper around [minified-civitai/](https://github.com/CurtisDS/minified-civitai/) to calculate the hashes of the models in a folder and match them to ids for minified-civitai to use.
> It also generates a simple .md with some info about the model and downloads the preview images, both in the folder where each model is located.

have you looked at [generateHTMLPreviews.py](https://github.com/CurtisDS/minified-civitai/blob/main/generateHTMLPreviews.py)? most of that functionality already exists. Just FYI.
