### ISSUE TITLE
can send preview images to "PNG info" or copy images File address?

### ISSUE THREAD

**Issue by hahajaja** [CurtisDS/sd-model-preview-xd#13]
Any ideas how this can be solved thx?

**Comment by CurtisDS** [comment]
What are you trying to do? There is already an ability to copy meta data, is there a particular reason you want to be able to send the image to PNG Info?

If you haven't moved the location of your preview files to a [folder outside of a1111](https://github.com/CurtisDS/sd-model-preview-xd#changing-default-directories) you can copy the file address just by right clicking on the image and copying the image link and the file path is what appears after "file=".
Example: http://127.0.0.1:7860/file=models/Stable-diffusion/MyModel.png

**Comment by unai-ndz** [comment]
Sending to PNG info and then to txt2img would be faster than copying the metadata and inputting everything manually.

**Comment by CurtisDS** [comment]
> Sending to PNG info and then to txt2img would be faster than copying the metadata and inputting everything manually.

hit copy meta data, click on txt2img, paste, and click the read generated parameters button.... not that complicated. Its a bunch of work for me and all it does is save you from having to hit paste. I still dont see the benefit.

**Comment by unai-ndz** [comment]
I didn't know about `read generated parameters button`, that makes it so much faster. Knowing this I agree with you.
