### ISSUE TITLE
[Bug?]: Model preview not working anymore

### ISSUE THREAD

**Issue by Woisek** [CurtisDS/sd-model-preview-xd#16]
It looks like Model Preview doesn't work anymore with https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81
The page is empty, the dropdown not working/available.

Any suggestions?

**Comment by CurtisDS** [comment]
It sounds like A1111 is really buggy right now. You can revert your a1111 install to get back to a working version. Last Friday there were a ton of commits, so I'm expecting the same today. I will probably wait until Sunday for things to settle down and then I'll look to see if there are still issues that need to be addressed.

**Comment by Woisek** [comment]
OK, it's not that urgent, I just wanted to let you know. Thanks for the response.

**Comment by CurtisDS** [comment]
436605fdb0a18728dcad05e91d0e6c4167e482a5 should fix this. Let me know if you're still seeing an issue.

**Comment by Wffv9FNa** [comment]
Was having the same issue and the new commit fixed it for me. Thanks!

**Comment by Woisek** [comment]
Yes, is fixed (sorry for late response).
