### ISSUE TITLE
The tab won't appear

### ISSUE THREAD

**Issue by Delocca** [CurtisDS/sd-model-preview-xd#17]
Error:

```
Error executing callback ui_tabs_callback for /xxx/SD/extensions/sd-model-preview-xd/scripts/modelpreview.py
Traceback (most recent call last):
  File "/xxx/SD/modules/script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "/xxx/SD/extensions/sd-model-preview-xd/scripts/modelpreview.py", line 680, in on_ui_tabs
    gr.HTML(elem_id='modelpreview_xd_setting', value='<script id="modelpreview_xd_setting_json" type="application/json">{ "LimitSize": ' + ( "true" if shared.opts.model_preview_xd_limit_sizing else "false" ) + ' }</script>', visible=False)
  File "/xxx/SD/modules/shared.py", line 467, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'model_preview_xd_limit_sizing'
```

**Comment by CurtisDS** [comment]
What version of Automatic1111 are you on?

**Comment by CurtisDS** [comment]
I'm not sure why I wasn't seeing the same error, but I removed all reference to that old setting now so if you update the extension it shouldn't get that error.

**Comment by BaconNori** [comment]
i was having the same issue , i had to reinstall automatic1111 and i am currently using 
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81

I added 
**git checkout a9eab236d7e8afa4d6205127904a385b2c43bb24** 
to the webui-user.bat file

I was on  4ab32997 (Tue Apr 4 18:54:10 2023) version of this extension, it still didn't work but i saw an update today
i update the version it was working again.

**Comment by Delocca** [comment]
It works after updating both Auto and the extension, thanks!

**Comment by CurtisDS** [comment]
ok good to hear
