### ISSUE TITLE
[Question] What Automatic1111 Webui Commit are you using?

### ISSUE THREAD

**Issue by TFWol** [CurtisDS/sd-model-preview-xd#21]
Hey @CurtisDS, could you tell me the webui commit number you're using?
I don't want to spend an absurd amount of time looking for a stable commit.

I'm currently on [803d44c4](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/803d44c4)

**Comment by CurtisDS** [comment]
I'm on the latest [22bcc7be428c94e9408f589966c2040187245d81](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81). Haven't run into any real issues. The worst thing I've had is problems with Anything V3 VAE (which have always been there) and when I use hires fix it sometimes sits forever at 100%... but it eventually does finish. I also only use the previews xd, control net, and the lycoris extensions. Nothing crazy.

**Comment by TFWol** [comment]
Sweet, thanks for the insight.
