### ISSUE TITLE
Add to the master extensions list

### ISSUE THREAD

**Issue by n15g** [CurtisDS/sd-model-preview-xd#24]
It doesn't look like this plugin has made it into the master extension list yet, https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions.
Any objections to adding it in?

**Comment by CurtisDS** [comment]
no I dont have an issue with that

**Comment by n15g** [comment]
Awesome. I'll submit a PR to the master list once #23 is in, so it doesn't cause any issues with people on the vladmandic port.

**Comment by n15g** [comment]
PR on the master list for reference: https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/53
