### ISSUE TITLE
Do not recognize metadata on jpg

### ISSUE THREAD

**Issue by ghost** [CurtisDS/sd-model-preview-xd#27]
Metadata work with png files but not with jpg.

if I drop a .jpg/.jpeg in PNG Info tab the metadata is show but the metadata for the same jpg is not copyable in model preview. 
it's important because loading jpg/jpeg are more fast than png I think and images from civitai use jpeg extension also

Two another qol points is to have separated sub folders preview for model previews to simulate sub categories sub folders, with a configurable preview size because the preview are a bit little on large screen

thank for this good mod

**Comment by CurtisDS** [comment]
Hmmm, I wrote an app to add meta data to pictures and it didn't work with jpgs... but I'll have another look at it.

**Comment by CurtisDS** [comment]
sorry I just saw this second point:

> Two another qol points is to have separated sub folders preview for model previews to simulate sub categories sub folders, with a configurable preview size because the preview are a bit little on large screen

Can you explain this further? I'm not entirely sure what you're looking for.
