### ISSUE TITLE
Interface broken in Automatic1111 v1.6.0

### ISSUE THREAD

**Issue by Kuzlata** [CurtisDS/sd-model-preview-xd#32]
With the extension installed the UI gets broken. See the pictures provided below

Extension Off
![1](https://github.com/CurtisDS/sd-model-preview-xd/assets/83128759/c966e5a2-c7fe-4b01-8e3e-c9f0e9ae3ab0)

Extension On
![2](https://github.com/CurtisDS/sd-model-preview-xd/assets/83128759/054fcf95-9313-46e1-807d-429a09c4a4b7)

The UI is cut into half. This was tested on Firefox and Edge.
No error messages in terminal.

Hope you can fix it.

**Comment by CurtisDS** [comment]
I am not able to replicate this for the txt2img and img2img tabs oddly but it was happening in the other tabs. The next commit should hopefully fix this.

**Comment by Kuzlata** [comment]
The latest commit fixed this issue. All good now. 
Thank you!
