### ISSUE TITLE
[Bug] TypeError.

### ISSUE THREAD

**Issue by LLKoder** [CurtisDS/sd-model-preview-xd#33]
![2023-09-02_11-14](https://github.com/CurtisDS/sd-model-preview-xd/assets/50442676/8d630e88-8377-49d0-a843-b4277cf0709c)

**Comment by CurtisDS** [comment]
thanks, found the issue and will be fixed in next commit. You should be safe ignoring the error until then, it shouldn't actually affect the extension.
