### ISSUE TITLE
[Bug]: Some console error

### ISSUE THREAD

**Issue by LLKoder** [CurtisDS/sd-model-preview-xd#35]
On start up I see some console error:

```
...\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioUnusedKwargWarning: You have unused kwarg parameters in Button, please remove them: {'type': 'secondary'}
  res = original_IOComponent_init(self, *args, **kwargs)
```

If add-on will turn off error will disappear either.

version: v1.6.0
python: 3.10.11
torch: 2.0.1+cu118
xformers: 0.0.20
gradio: 3.41.2
checkpoint: [171c237b86]

**Comment by CurtisDS** [comment]
Im not seeing that error. Are you on the latest version of the extension?

**Comment by LLKoder** [comment]
Yes...

![2023-09-16_22-59](https://github.com/CurtisDS/sd-model-preview-xd/assets/50442676/35227a3e-4ad0-4bfa-be44-8180d5113a0e)

**Comment by CurtisDS** [comment]
I have not been able to replicate the error. It appears to just be a warning and you could probably safely ignore it. That said I had a look through the code for anything referencing "type secondary" and removed the one occurrence. So update and see if it goes away.

**Comment by LLKoder** [comment]
Thanks! Now all ok.
