### ISSUE TITLE
[Bug]: 本地化错误和.lora、embeddings、hypernetworks中文件名错误

### ISSUE THREAD

**Issue by aylz10** [CurtisDS/sd-model-preview-xd#36]
抱歉我的英文不好，害怕问题描述不清楚，所以直接使用中文提交问题。
1.本地化错误：
当使用[stable-diffusion-webui-localization-zh_Hans]插件进行本地化后，[sd-model-preview-xd]tab中的“Checkpoints”被本地化为了"模型"，造成点击附加网络中Checkpoints里的[sd-model-preview-xd]按钮失效
分析原因：
[sd-model-preview-xd]按钮识别tab名称不符
临时解决办法：
把sd-model-preview-xd\javascript\event_handlers.js中的modelToSelect = "Checkpoints";改为modelToSelect = "模型";，case "Checkpoints":改为case "模型":
2.lora、embeddings、hypernetworks中如果名称包含 “.”和大写字母 那么点击[sd-model-preview-xd]按钮无法正常获取元数据，例如：2.5D_sweetprettygirl_v1.safetensors这个lora。
分析原因：
sd-model-preview-xd获取的附加网络列表名字是不带后缀的，比如2.5D_sweetprettygirl_v1.safetensors这个lora，获取到的是2.5D_sweetprettygirl_v1这个名字，clean_modelname(modelname)函数将其分割为了2和.5D_sweetprettygirl_v1后缀，然后进行后缀变更小写为.5_sweetprettygirl_v1，合并后名字变成了2.5d_sweetprettygirl_v1，所以无法读取元数据
临时解决办法：
将def clean_modelname(modelname):函数中的
name, ext = os.path.splitext(modelname)
ext = ext.lower()
modelname = name + ext
语句删除

**Comment by CurtisDS** [comment]
Thanks for pointing these out. If you update the extension, these issues should be resolved. If you still have problems, please let me know.
