### ISSUE TITLE
[Feature Request] Option to show prompt data when hovering over Copy button

### ISSUE THREAD

**Issue by TFWol** [CurtisDS/sd-model-preview-xd#39]
The button that lets you copy prompt metadata to clipboard has been super handy. Is there a way to show that information by just hovering over the button?

**Comment by CurtisDS** [comment]
Can you explain why you would want that as a feature? How would you use it?

**Comment by CurtisDS** [comment]
As its been about 3 weeks im going to close this. Will reopen if you get back to me about what you are looking for.
