### ISSUE TITLE
[Feature Request] Save the model image files locally, rather than re-download them every time

### ISSUE THREAD

**Issue by mx** [CurtisDS/sd-model-preview-xd#40]
This is a wonderful extension. I noticed that the UI is re-downloading all the sample images whenever the UI is loaded. It would be helpful if instead it could download them once and save to disk. That way the extension could be used when offline or when Civitai is down.

**Comment by mx** [comment]
More details: the image URLs are coming from the .civitai.info files. They point to a URL on civitai (obviously!). So I wonder if they could be written locally and then the URL rewritten.

**Comment by CurtisDS** [comment]
for the .civitai.info images it is probably possible. I'll look into it

**Comment by CurtisDS** [comment]
added in commit 54a63489addc0dad48dc43ecbb1b7f45642b46f2
