### ISSUE TITLE
Make Model Preview Extension work with hidden folders

### ISSUE THREAD

**Issue by JoseQui77** [CurtisDS/sd-model-preview-xd#42]
When using folder for previews, the folders also appear in the Extra Networks cards, and having lots of models, Extra networks get bloated with folders that have no use there.

I was able to hide the folder in Extra Networks making the folder to start with a period ".", but then Model Previews won´t find the folder.  

Can you make this extension to work with hidden folders? (starting with ".").

**Comment by CurtisDS** [comment]
Do you need it to be a hidden folder or do you just not want to see it in the subfolder list on the Extra Networks page? As far as I can tell A1111 doesnt let you link to hidden folders through the gradio front end. But I can add something that would go through and hide all the subfolders in the Extra Network tab that start with a specific string. Like say "Previews_"

**Comment by CurtisDS** [comment]
I added some JavaScript that will hide subfolders from the extra networks subfolder button list if the folder starts with an underscore (example `_previews`) in commit 54a63489addc0dad48dc43ecbb1b7f45642b46f2

**Comment by JoseQui77** [comment]
> I added some JavaScript that will hide subfolders from the extra networks subfolder button list if the folder starts with an underscore (example `_previews`) in commit [54a6348](https://github.com/CurtisDS/sd-model-preview-xd/commit/54a63489addc0dad48dc43ecbb1b7f45642b46f2)

Thank you.
