### ISSUE TITLE
[Feature Request](Low Pri) Have Preview Images sorted by Natural Order

### ISSUE THREAD

**Issue by TFWol** [CurtisDS/sd-model-preview-xd#5]
Currently the images are sorted:
```
model.10.png
model.11.png
model.6.png
```

Should be:
```
model.6.png
model.10.png
model.11.png
```

It would make organizing images a bit easier when naming them.

**Comment by CurtisDS** [comment]
Im pretty sure its ordering that way because of how windows orders files. You could rename the files to `model.06.png` and it will probably sort the way you want.

**Comment by TFWol** [comment]
Windows explorer shows the correct order. It's a python on windows thing.
I usually see **natsort** library being used for stuff like that.

> You could rename the files to model.06.png and it will probably sort the way you want.

yeah I've been padding the files with 0's as a workaround.

**Comment by CurtisDS** [comment]
If it is solved by just naming your files with padded 0s when you want numerical ordering... Is that not good enough?

Trying to add numerical sorting gets annoying. Its slightly easier with the strict name matching but even then there are edge cases that complicate things.

For example... how would you sort this set of files:

```
model.10.png
model.preview.8.png
model.png
model.02.png
model.preview.png
model.2.png
```

Do you go based solely on the number? Do .preview files get sorted in with the rest or later? or before? What about when they dont have a number? etc.

And thats not even getting into the can of worms that trying to numerically order the loose name matching would be.

I suppose I could add something only for strict naming.

**Comment by TFWol** [comment]
I didn't bother with `preview`. I just stuck with model.001.png, model.002.png, etc. once I saw the order being weird.

Oh yeah, don't worry about trying to implement a sorting fix if it's too much of a pain. Padding with 0's is perfectly viable.

It's a feature request, but super low pri.
